package com.example.cuppingapp;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;

public class AddCoffeeActivity extends AppCompatActivity {

    private EditText editTextCoffeeID, editTextCoffeeName, editTextCoffeeOrigin, editTextProcess, editTextVarietal;
    private CoffeeDao coffeeDao;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add_coffee);

        coffeeDao = new CoffeeDao(this);

        // Initialize UI elements
        editTextCoffeeID = findViewById(R.id.editTextCoffeeID);
        editTextCoffeeName = findViewById(R.id.editTextCoffeeName);
        editTextCoffeeOrigin = findViewById(R.id.editTextCoffeeOrigin);
        editTextProcess = findViewById(R.id.editTextProcess);
        editTextVarietal = findViewById(R.id.editTextVarietal);
        Button buttonAddCoffee = findViewById(R.id.buttonAddCoffee);

        // Set onClickListener for the button
        buttonAddCoffee.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                saveCoffee();
            }
        });
    }

    private void saveCoffee() {
        String name = editTextCoffeeName.getText().toString().trim();
        String origin = editTextCoffeeOrigin.getText().toString().trim();
        String process = editTextProcess.getText().toString().trim(); // Optional
        String varietal = editTextVarietal.getText().toString().trim(); // Optional

        if (name.isEmpty() || origin.isEmpty()) {
            Toast.makeText(this, "Please fill all required fields", Toast.LENGTH_SHORT).show();
            return;
        }

        // Create a new Coffee object without coffeeID (it will be auto-generated by the database)
        Coffee newCoffee = new Coffee(name, origin, process, varietal);
        CoffeeDao coffeeDao = new CoffeeDao(this);
        coffeeDao.addCoffee(newCoffee);

        Toast.makeText(this, "Coffee added!", Toast.LENGTH_SHORT).show();
        finish();  // Close activity
    }
}
